name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Actualiza a la versión v1 de setup-swift
    - name: Set up Swift 6.0
      uses: apple/actions/setup-swift@v1
      with:
        swift-version: '6.0.0'

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
