name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Instalar Swift manualmente
    - name: Install Swift 6.0.0
      run: |
        curl -sSL https://swift.org/download/#releases -o swift-download.html
        swift_version="6.0.0"
        download_url=$(grep -o 'https://swift.org/builds.*\.pkg' swift-download.html | head -n 1)
        curl -sSL "$download_url" -o swift.pkg
        sudo installer -pkg swift.pkg -target /

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
