name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Instalar Swift manualmente
    - name: Install Swift 6.0.0
      run: |
        curl -sSL https://swift.org/builds/swift-6.0.0-release/xcode/swift-6.0.0-RELEASE/swift-6.0.0-RELEASE-osx.pkg -o swift.pkg
        sudo installer -pkg swift.pkg -target /

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
